# Generated by Django 4.2.3 on 2023-08-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20, verbose_name='Nom ')),
                ('prenoms', models.CharField(max_length=30, verbose_name='Prenoms')),
                ('genre', models.CharField(choices=[('feminin', 'Feminin'), ('masculin', 'Masculin')], max_length=20, verbose_name='Genre')),
                ('fonction', models.CharField(max_length=30, verbose_name='Fonction')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('contact', models.CharField(max_length=20, verbose_name='Contact')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('nationalite', models.CharField(max_length=20, verbose_name='Nationalite')),
                ('valide', models.CharField(choices=[('valider', 'Valider'), ('non_valider', 'Non Valider')], max_length=20, verbose_name='valider la personne')),
                ('statut', models.CharField(default='non', max_length=3, verbose_name='choix')),
            ],
        ),
        migrations.RenameField(
            model_name='recherche_emploi',
            old_name='emploi_acteur',
            new_name='acteur_emploi',
        ),
        migrations.RemoveField(
            model_name='recherche_emploi',
            name='paiement',
        ),
        migrations.AddField(
            model_name='recherche_emploi',
            name='statut',
            field=models.CharField(default='ok', max_length=3, verbose_name='choix'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recherche_emploi',
            name='valide',
            field=models.CharField(choices=[('valider', 'Valider'), ('non_valider', 'Non Valider')], default='valider', max_length=20, verbose_name='valider la personne'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acteur',
            name='statut',
            field=models.CharField(default='non', max_length=3, verbose_name='choix'),
        ),
        migrations.AlterField(
            model_name='deces',
            name='statut',
            field=models.CharField(default='non', max_length=3, verbose_name='choix'),
        ),
        migrations.AlterField(
            model_name='naissance',
            name='statut',
            field=models.CharField(default='non', max_length=3, verbose_name='choix'),
        ),
    ]
