# Generated by Django 4.2.3 on 2023-08-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_venant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acteur',
            name='valide',
            field=models.CharField(choices=[('valider', 'Valider'), ('non_valider', 'Non Valider')], default='valider', max_length=20, verbose_name='valider la personne'),
        ),
    ]
