# Generated by Django 4.2.3 on 2023-08-15 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_acteur_valide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acteur',
            name='statut',
            field=models.CharField(default='ok', max_length=3, verbose_name='choix'),
        ),
        migrations.AlterField(
            model_name='acteur',
            name='valide',
            field=models.BooleanField(default=1, verbose_name='valider la personne'),
        ),
        migrations.AlterField(
            model_name='deces',
            name='valide',
            field=models.BooleanField(default=0, verbose_name='valider la personne'),
        ),
        migrations.AlterField(
            model_name='naissance',
            name='mode_naissance',
            field=models.CharField(max_length=20, verbose_name="nom de l'hopital"),
        ),
        migrations.AlterField(
            model_name='naissance',
            name='valide',
            field=models.BooleanField(default=0, verbose_name='valider la personne'),
        ),
        migrations.AlterField(
            model_name='recherche_emploi',
            name='valide',
            field=models.BooleanField(default=0, verbose_name='valider la personne'),
        ),
        migrations.AlterField(
            model_name='venant',
            name='valide',
            field=models.BooleanField(default=0, verbose_name='valider la personne'),
        ),
    ]
