# Generated by Django 4.2.3 on 2023-08-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_acteur_statut_alter_acteur_valide_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acteur',
            name='age_acteur',
            field=models.CharField(default='', max_length=20, verbose_name="age del'acteur"),
        ),
    ]
