# Generated by Django 4.2.3 on 2023-08-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_acteur_age_acteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acteur',
            name='email_acteur',
            field=models.EmailField(default='', max_length=254, verbose_name="email de l'acteur"),
        ),
    ]
