# Generated by Django 4.2.3 on 2023-08-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_alter_acteur_email_acteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacie',
            name='garde',
            field=models.BooleanField(default=1, verbose_name='valider la personne'),
        ),
    ]
